# Generated by Django 3.0.8 on 2020-07-21 13:26

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='post',
            options={'managed': True, 'verbose_name': 'Posts', 'verbose_name_plural': 'Postss'},
        ),
        migrations.AlterModelTable(
            name='post',
            table='Posts',
        ),
    ]
