# Generated by Django 3.0.8 on 2020-07-19 09:55

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('job', '0002_auto_20200719_1152'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='job',
            options={},
        ),
    ]
